Added support for HAProxy's PROXY protocol v2
haveachin/infrared pull request #17
Opened 2021-01-03 23:57 UTC by CM8DoubleCheck

2021-01-04 10:04 UTC, haveachin requested changes
Left you a few comments

2021-01-04 21:38 UTC, dada513 approved these changes

2021-01-05 19:11 UTC, CM8DoubleCheck commented on mc/conn.go
> +func DialTimeout(addr string, proxyProtocol bool, timeout time.Duration) (Conn, error) {
No specific reason, I'll move it to the end

2021-01-05 21:52 UTC, CM8DoubleCheck commented
I realized one oversight, I needed to pass the incoming client connection address to DialTimeout() rather than getting net.DialTimeout()'s remoteAddr (which would just return the connecting server's connection address). That's fixed and I verified it's working.

2021-01-06 01:32 UTC, haveachin approved these changes

2021-01-06 01:33 UTC, haveachin commented
Thanks for your contribution :)

2021-01-06 01:33 UTC, merged